[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/AstroNvim/AstroNvim"

[".config/nvim/lua/user"]
    type = "git-repo"
    url = "https://github.com/johnstegeman/astro_user"
    refreshPeriod = "168h"

[".tmux"]
    type = "git-repo"
    url = "https://github.com/gpakosz/.tmux.git"
    refreshPeriod = "168h"