[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/AstroNvim/AstroNvim"

[".config/nvim/lua/user"]
    type = "git-repo"
    url = "https://github.com/johnstegeman/astro_user"
    refreshPeriod = "168h"

[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"
