[tools]
doggo = "latest"
entireio-cli = "latest"
gh = "latest"
java = "27"
jbang = "latest"
jq = "latest"
lua = "latest"
luajit = "latest"
neovim = "latest"
trufflehog = "latest"
hunk = "latest"
terraform = "latest"
worktrunk = "latest"
"github:agavra/tuicr" = "latest"
"github:gastownhall/beads" = "latest"
