[tools]
atuin = "latest"
bat = "latest"
bottom = "latest"
# btop = "latest"
bun = "latest"
carapace = "latest"
clang-format = "latest"
coreutils = "latest"
delta = "latest"
dua = "latest"
duf = "latest"
fd = "latest"
fzf = "latest"
just = "latest"
make = "latest"
node = "latest"
python = "latest"
ripgrep = "latest"
sqlite = "latest"
tmux = "latest"
tree-sitter = "latest"
uv = "latest"
zellij = "latest"
zoxide = "latest"
