[tools]
doggo = "latest"
entireio-cli = "latest"
gh = "latest"
java = "26"
jbang = "latest"
jq = "latest"
lua = "latest"
luajit = "latest"
neovim = "latest"
trufflehog = "latest"
hunk = "latest"
terraform = "latest"
worktrunk = "latest"
