[theme]
name = "tokyonight-night"

[colors]
AlertInfo = "#9ece6a"
AlertWarn = "#e0af68"
AlertError = "#f7768e"
Annotation = "#7dcfff"
Base = "#c0caf5"
Guidance = "#565f89"
Important = "#f7768e"
Title = "#7aa2f7"
