[colors]
ansi = [ "#15161d", "#e77d8f", "#a8cd76", "#d8b172", "#82a1f1", "#b69bf1", "#90cdfa", "#aab1d3" ]
brights = [ "#424866", "#e77d8f", "#a8cd76", "#d8b172", "#82a1f1", "#b69bf1", "#90cdfa", "#c2caf1" ]

background = "#1a1b25"
foreground = "#c2caf1"

#compose_cursor = '#ebde76'
#cursor_bg = "#eee9fc"
#cursor_border = "#eee9fc"
cursor_fg = "#c2caf1"

selection_bg = "#2a3454"
selection_fg = "#c2caf1"

#scrollbar_thumb = '#3f3951'
#split = '#938aad'

#[colors.indexed]

#[colors.tab_bar]
#background = "#282433"

#[colors.tab_bar.active_tab]
#bg_color = "#282433"
#fg_color = "#e965a5"
#intensity = "Normal"
#underline = "None"
#italic = false
#strikethrough = false

#[colors.tab_bar.inactive_tab]
#bg_color = "#282433"
#fg_color = "#938aad"
#intensity = "Normal"
#italic = false
#strikethrough = false
#underline = "None"

#[colors.tab_bar.inactive_tab_hover]
#bg_color = "#e192ef"
#fg_color = "#eee9fc"
#intensity = "Normal"
#italic = false
#strikethrough = false
#underline = "None"

#[colors.tab_bar.new_tab]
#bg_color = "#282433"
#fg_color = "#938aad"
#intensity = "Normal"
#italic = false
#strikethrough = false
#underline = "None"

#[colors.tab_bar.new_tab_hover]
#bg_color = "#e192ef"
#fg_color = "#eee9fc"
#intensity = "Normal"
#italic = true
#strikethrough = false
#underline = "None"

[metadata]
name = 'Solarized Osaka Dark'
origin_url = ''