## Flox Environment Manifest -----------------------------------------
##
##   _Everything_ you need to know about the _manifest_ is here:
##
##               https://flox.dev/docs/concepts/manifest
##
## -------------------------------------------------------------------
# Flox manifest version managed by Flox CLI
version = 1


## Install Packages --------------------------------------------------
##  $ flox install gum  <- puts a package in [install] section below
##  $ flox search gum   <- search for a package
##  $ flox show gum     <- show all versions of a package
## -------------------------------------------------------------------
[install]
jq.pkg-path = "jq"
asciinema.pkg-path = "asciinema"
awscli2.pkg-path = "awscli2"
bat.pkg-path = "bat"
bottom.pkg-path = "bottom"
cmake.pkg-path = "cmake"
dua.pkg-path = "dua"
eza.pkg-path = "eza"
fio.pkg-path = "fio"
fish.pkg-path = "fish"
git.pkg-path = "git"
delta.pkg-path = "delta"
gtypist.pkg-path = "gtypist"
htop.pkg-path = "htop"
httpie.pkg-path = "httpie"
jbang.pkg-path = "jbang"
kompose.pkg-path = "kompose"
lazygit.pkg-path = "lazygit"
librsvg.pkg-path = "librsvg"
luarocks.pkg-path = "luarocks"
neovim.pkg-path = "neovim"
nmap.pkg-path = "nmap"
nodejs.pkg-path = "nodejs"
pkgconf.pkg-path = "pkgconf"
subversion.pkg-path = "subversion"
tmux.pkg-path = "tmux"
virtualenv.pkg-path = "virtualenv"
wget.pkg-path = "wget"
yarn.pkg-path = "yarn"
zellij.pkg-path = "zellij"
zlib.pkg-path = "zlib"
zsh.pkg-path = "zsh"
uv.pkg-path = "uv"
google-cloud-sdk.pkg-path = "google-cloud-sdk"
temurin-bin-17.pkg-path = "temurin-bin-17"
# gum.pkg-path = "gum"
# gum.version = "^0.14.5"


## Environment Variables ---------------------------------------------
##  ... available for use in the activated environment
##      as well as [hook], [profile] scripts and [services] below.
## -------------------------------------------------------------------
[vars]
# INTRO_MESSAGE = "It's gettin' Flox in here"


## Activation Hook ---------------------------------------------------
##  ... run by _bash_ shell when you run 'flox activate'.
## -------------------------------------------------------------------
[hook]
# on-activate = '''
#   # -> Set variables, create files and directories
#   # -> Perform initialization steps, e.g. create a python venv
#   # -> Useful environment variables:
#   #      - FLOX_ENV_PROJECT=/home/user/example
#   #      - FLOX_ENV=/home/user/example/.flox/run
#   #      - FLOX_ENV_CACHE=/home/user/example/.flox/cache
# '''


## Profile script ----------------------------------------------------
## ... sourced by _your shell_ when you run 'flox activate'.
## -------------------------------------------------------------------
[profile]
# common = '''
#   gum style \
#   --foreground 212 --border-foreground 212 --border double \
#   --align center --width 50 --margin "1 2" --padding "2 4" \
#     $INTRO_MESSAGE
# '''
## Shell specific profiles go here:
# bash = ...
# zsh  = ...
# fish = ...


## Services ----------------------------------------------------------
##  $ flox services start             <- Starts all services
##  $ flox services status            <- Status of running services
##  $ flox activate --start-services  <- Activates & starts all
## -------------------------------------------------------------------
[services]
# myservice.command = "python3 -m http.server"


## Other Environment Options -----------------------------------------
[options]
# Systems that environment is compatible with
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
# Uncomment to disable CUDA detection.
# cuda-detection = false
