#? Config file for btop v. 1.4.0

color_theme = "rose-pine"
theme_background = True
truecolor = True
shown_boxes = "cpu mem net proc"
update_ms = 2000
proc_sorting = "cpu lazy"
proc_reversed = False
proc_tree = False
tree_depth = 3
proc_colors = True
proc_gradient = True
proc_per_core = False
proc_mem_bytes = True
cpu_graph_upper = "total"
cpu_graph_lower = "total"
cpu_invert_lower = True
cpu_single_graph = False
show_uptime = True
check_temp = True
show_coretemp = True
temp_scale = "celsius"
show_cpu_freq = True
draw_clock = "%X"
background_update = True
custom_cpu_name = ""
disks_filter = ""
mem_graphs = True
show_swap = False
swap_disk = False
show_disks = True
only_physical = True
use_fstab = False
show_io_stat = False
io_mode = False
io_graph_combined = False
io_graph_speeds = ""
net_download = "10M"
net_upload = "10M"
net_auto = True
net_sync = False
net_color_fixed = False
net_iface = ""
show_battery = True
show_init = False
update_check = False
log_level = "WARNING"
