[settings]
python.uv_venv_auto = "source"
experimental = true
# idiomatic_version_file_enable_tools = ["swift"]
auto_install = true
jobs = 4

[tools]
java = "21"
#"ubi:ll-nick/leadr" = "latest"
doggo = "latest"
bun = "latest"
python = "latest"
awscli = { version = "latest", symlink_bins = "true" }
kubectl = "latest"
helm = "latest"
kompose = "latest"
trufflehog = "latest"
#"pipx:headroom-ai" = { version = "latest", extras = "all" }
node = "latest"
claude-code = "latest"
rtk = "latest"
codex = "latest"

# migrated from brew
atuin = "latest"
bat = "latest"
bottom = "latest"
btop = "latest"
carapace = "latest"
clang-format = "latest"
coreutils = "latest"
delta = "latest"
dua = "latest"
duf = "latest"
entire = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gcloud = "latest"
gh = "latest"
git-lfs = "latest"
jbang = "latest"
jj = "latest"
jq = "latest"
just = "latest"
lua = "latest"
luajit = "latest"
make = "latest"
mas = "latest"
neovim = "latest"
ollama = "latest"
opencode = "latest"
ripgrep = "latest"
sqlite = "latest"
tmux = "latest"
tree-sitter = "latest"
uv = "latest"
zellij = "latest"
zoxide = "latest"
"1password" = "latest"
"1password-cli" = "latest"
claude = "latest"
