[settings]
python.uv_venv_auto = "source"
experimental = true
# idiomatic_version_file_enable_tools = ["swift"]
auto_install = true
jobs = 4

[tools]
java = "21"
#"ubi:ll-nick/leadr" = "latest"
doggo = "latest"
bun = "latest"
python = "latest"
awscli = { version = "latest", symlink_bins = "true" }
kubectl = "latest"
helm = "latest"
kompose = "latest"
trufflehog = "latest"
